---
title: "FinalReplication"
author: "cjlw2020"
date: "12/11/2019"
output: html_document
---
Packages Needed
```{r}
library(lme4)
library(car)
library(optimx)
library(deSolve)
```

Needed
```{r}
 setwd("C:/Users/clint/Desktop/AN597_Project/Individule/doi_10.5061_dryad.0r31r__v1")
df <- read.table("hog.txt", header = TRUE)
head(df)
```

```{r}
summary(df)
```
```{r}
plot(df)
```

Non-linear least squares attempt:
```{r}
y <- c(df$mass)
x1 <- c(df$age)
x <- age1/365 #Changes age from days to years
m <-nls(y~a*x/(b+x))
cor(y,predict(m)) #Shows how well the model fits
```

```{r}
plot(x,y)
lines(x,predict(m),lty=2,col="red",lwd=3)
```
Guessing Starting parameters
Find Rate of Growth
```{r}
RoG <- (log(max(y)/min(y)))/(max(x)) 
RoG #Rate of Growth, didnt work
```

```{r}
a_start<- 0.2 #param a is the y value when "x=0"
b_start<- 0.06523683 #b is the growth rate
```

```{r}
k <-nls(y~a*exp(-b*x),start=list(a=a_start,b=b_start))
cor(y,predict(k)) 
```
```{r}
plot(x,y)
lines(x,predict(k),col="red",lty=2,lwd=3) #This is not working properly
```

```{r}
log_growth <- function(Time, State, Pars) {
  with(as.list(c(State, Pars)), {
    dN <- R*N*(1-N/K)
    return(list(c(dN)))
  })
}
```











```{r}
t1 <- max(y) #This will give us the maximum value from the data, which we're saying is our starting  value for "theta1", the parameter for the asymptote of growth

new <- lm(logit(y/t1)~x,data=df) #this gives us the logistic values for BW divided by the asymptote (an approximation of the curve values for each individual)

t2 <- new$coef[1] #this is our starting value for "theta2", which is our parameter of the midpoint of the growth curve

t3 <- new$coef[2] #this is our starting value for "theta3", which is our parameter of the rate of growth

```

Logistic Model
```{r}
l <- function(AGE,theta1,theta2,theta3) {theta1/(1+exp(-(theta2+theta3*AGE)))} #here we're writing out the function for logistic growth (this is how we tell R what function we're using to model growth... like the function in the table in your paper), which estimates parameters "theta1", "theta2", and "theta3" for changes in a variable (like "BW") based on "AGE".

model.logistic <- nls(y ~ theta1/(1+exp(-(theta2+theta3*x))), data=df, start=list(theta1=t1,theta2=t2,theta3=t3))
model.logistic
```
or...
```{r}
model.logistic <- nls(mass ~ l(age,theta1,theta2,theta3), data=df, start=list(theta1=t1,theta2=t2,theta3=t3))

summary(model.logistic) #this should give you the estimates for "theta1", "theta2", and "theta3" based on the data.

#For Gompertz, everything the same, but the equation/function used (again, for Lord you'd get this from translating the model equations in your table to R code):
```
```{r}
plot(x,y)
lines(model.logistic)
```

Gompertz Modle
```{r}
g <- function(age,theta1,theta2,theta3){theta1*exp(-exp(-(theta3*(age-theta2))))}

model.gompertz <- nls(mass ~ theta1*exp(-exp(-(theta3*(age-theta2)))), data=df, start=list(theta1=t1,theta2=t2,theta3=t3))
```
or...
```{r}
model.gompertz <- nls(mass ~ g(age,theta1,theta2,theta3), data=df, start=list(theta1=t1,theta2=t2,theta3=t3))

summary(model.gompertz)
```


